-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 13:03:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sport_shoes_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sport_shoes_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sport_shoes_shop` DEFAULT CHARACTER SET utf8 ;
USE `sport_shoes_shop` ;

-- -----------------------------------------------------
-- Table `sport_shoes_shop`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_shoes_shop`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(20) NOT NULL,
  `customer_email` VARCHAR(255) NOT NULL,
  `customer_phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_shoes_shop`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_shoes_shop`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_shoes_shop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_shoes_shop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NULL,
  `total_amount` DECIMAL(10,2) NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `sport_shoes_shop`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_shoes_shop`.`orders_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_shoes_shop`.`orders_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shoe_id` INT NOT NULL,
  `quantity` INT NULL,
  `orders_id` INT NOT NULL,
  PRIMARY KEY (`id`, `shoe_id`),
  INDEX `fk_orders_details_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_details_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `sport_shoes_shop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sport_shoes_shop`.`shoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport_shoes_shop`.`shoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brands_id` INT NOT NULL,
  `shoe_name` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NULL,
  `orders_details_id` INT NOT NULL,
  `orders_details_shoe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ shoes_brands_idx` (`brands_id` ASC) VISIBLE,
  INDEX `fk_ shoes_orders_details1_idx` (`orders_details_id` ASC, `orders_details_shoe_id` ASC) VISIBLE,
  CONSTRAINT `fk_ shoes_brands`
    FOREIGN KEY (`brands_id`)
    REFERENCES `sport_shoes_shop`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ shoes_orders_details1`
    FOREIGN KEY (`orders_details_id` , `orders_details_shoe_id`)
    REFERENCES `sport_shoes_shop`.`orders_details` (`id` , `shoe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
